notifications:
  email: false
language: node_js
node_js:
- 6.2.2
before_install:
- sudo apt-get update -qq
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: KqFx/j5S2YmGAmDgniWzLRXZ21UJQzm+dMGJA5B81pmgWlFyqJ1161oeBMM9asEJnAuvEpl5Zw7CbusFAFWPapaUAlu3cf3DJaalYPsiOlyWoKqVRIn9uyMaMMc7WQVLAfPPVUjyZDqbj/Q7acKYUac6r8Zk3bMrR8rkDM+ulHccmqU6iI4G6O4YjLrZdk7tiStcRYgI8sWnwLlKBaHTiVFcHtbVT4Kq0Rix2gUsGzhSSkqm+r5m07lpFjJGCYlnqQNYJG5YJQ38DfJPHAPHKTm0VTOYwJrt/GLur+BtIfgX4PrggyyzQVi9rAtfPThqidkC8sRb5IyHRFC/8oVGple0YIKuN0ZI/KD1YfV8or2ckwnId6fKSxhs8XFIiyMqUtarkn6CVVdUajQNK3Re6ACHZhEqBpRMsbB3SKSOfRpp+IpFKDUkx+2sC/vGuWx9zf/9NbMBWwDD1rMBw3dK9LFv/Og1+WR9qn89l/svKNaQG2Zx4D7hBlc1iakJF1H+v1zk+5G1COtUytw8QEoLFJbKQ+tT2NAr1C7DWrh05V9asEVKzy/qvDnJ+q4sxE9N2BnRSTmTRQxu1m2ke/elKIdpSO0GUe41ZQoOGmOFhjCOBn6hTpivKJj12EfK4VvdFfzz9nM05tJErd1aqxerAPqgspavJc6EHtph18QrM8I=
    app: songodoro
