notifications:
  email: false
language: node_js
node_js:
- 6.2.2
before_install:
- sudo apt-get update -qq
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: RPhBBVhhk6g8LM6JNo/qAExj7MQVYuhLb4cwPbtCjCvsAJ+GrFsQ9Q1OYkMdHCvxQcp9qhpHlzOUbzifKW2/aqM7SKvgInxyoYvb9x9WWSuYl5yPb4hmJy55jFQI3c/BHG1v5wAzXznv8OJSjcRf/jlOFr3RUpie3MslMZyOyP8DwwkiWIozI/kZAwTaBZ17Cgat4TQLlhtVr9vEjBRkS5XsNNbqWzgxz3uQSdh7Sxy5scB1XP7sFMPyKXxEnz5fvWQfX76cK5ENFRU6y6XCcDYUzzFlzmkfEp+cCvcuAYNIUC/rz154w5X4UxbNqGHirjE0qyiFDTo4x8qoj2NR6AD37rFEtkEwJFD3Zp9dfz1TiUilGnPufIy1q1J+Swvf4xZMV7ahJOjrVsDZZDF4Z6PfUQjifpg0q48ke4qpAuasl0oRICnZXAZFK4argGFNyZXDL6U91RICOykl8odPbZEl0N3GHCcR1l9+ICiriR/WLPBNsAYNBuxYtCzLOQSX4qumOPuYuRRJ0ysWqUuDkZ0mQoWwLnK8sNxymc1uVYyrNxOAXl/iKAHF9Mfj6ChdEVtl5IdO+AMEnEqhJlmchp16VbZz6ZprR92DW37pgzuJvvtxCrdMai+9cZqGFeg2BC99jTXmhrWgLob4zh0gv5YXzOl9g7MSK+8NL+V4YlM=
